// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Semogly.Core.Infrastructure.Data;

#nullable disable

namespace Semogly.Core.Infrastructure.Migrations
{
    [DbContext(typeof(SemoglyDbContext))]
    [Migration("20251219021132_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Semogly.Core.Domain.AccountContext.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Semogly.Core.Domain.AccountContext.Entities.Account", b =>
                {
                    b.OwnsOne("Semogly.Core.Domain.AccountContext.ValueObjects.CompositeName", "Name", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("varchar(20)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("varchar(30)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("varchar(30)")
                                .HasColumnName("middle_name");

                            b1.HasKey("AccountId");

                            b1.ToTable("account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("Semogly.Core.Domain.AccountContext.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("email_address");

                            b1.HasKey("AccountId");

                            b1.ToTable("account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("Semogly.Core.Domain.AccountContext.ValueObjects.LockOut", "Lockout", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("LockOutEndUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("lockout_end");

                            b1.Property<string>("LockOutReason")
                                .HasColumnType("text")
                                .HasColumnName("lockout_reason");

                            b1.HasKey("AccountId");

                            b1.ToTable("account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("Semogly.Core.Domain.AccountContext.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<string>("HashText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password_hashed");

                            b1.HasKey("AccountId");

                            b1.ToTable("account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("Semogly.Core.Domain.AccountContext.ValueObjects.VerificationCode", "VerificationCode", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("char(6)")
                                .HasColumnName("verification_code");

                            b1.Property<DateTime?>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("verification_expires_at");

                            b1.Property<DateTime?>("VerifiedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("verification_verified_at");

                            b1.HasKey("AccountId");

                            b1.ToTable("account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("Semogly.Core.Domain.SharedContext.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("AccountId");

                            b1.ToTable("account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Lockout");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Tracker")
                        .IsRequired();

                    b.Navigation("VerificationCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
